version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  servimotoserver:
    build:
      context: .
      dockerfile: ServiMotoServer/Dockerfile
    container_name: servimotoserver
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/servimoto.db"
    volumes:
      - servimotodata:/app/data

networks:
  default:
    name: my_network
    external: false

volumes:
  servimotodata:
